
sudo: required
dist: trusty

language: node_js
node_js:
  - "7"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

before_script:
  - npm run prod

script:
  - npm run dev